blank_issues_enabled: false
contact_links:
  - name: Bug report
    url: https://github.com/livepeer/comfystream/issues
    about: Please report bugs on our upstream issue tracker.
  - name: Feature request
    url: https://github.com/livepeer/comfystream/issues
    about: Please request features on our upstream issue tracker.
  - name: Question
    url: https://github.com/livepeer/comfystream/discussions/234
    about: Have a question? Ask them on our upstream discussions page.
